name: iteration burndown status action
description: provide burndown status of the current iteration in GitHub Project
author: otariidae

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: a GitHub token with read access to the project
    required: true
  login-name:
    description: organization name
    required: true
  project-number:
    description: project number
    required: true
  point-field-name:
    description: field name of estimated story points
    required: false
    default: 'points'
  iteration-field-name:
    description: field name of iteration
    required: false
    default: 'Iteration'
  status-field-name:
    description: field name of status
    required: false
    default: 'Status'

outputs:
  remaining-points:
    description:
      sum of points of remaining project items in the current iteration
  total-points:
    description: sum of points of all project items in the current iteration

runs:
  using: node20
  main: dist/index.js
